language: java
sudo: required
  
services:
  - docker
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export IMAGE_NAME=mamathakrishna/sample-app
- docker build -t mamathakrishna/sample-app .
- docker push mamathakrishna/sample-app
